# NUTS Mapping Creator

[NUTS](https://en.wikipedia.org/wiki/Nomenclature_of_Territorial_Units_for_Statistics) is a mapping schema to map the areas in the European Union. It has 3 levels and divides countries up but sems quite hard to get a simple mapping table in a non-ridiculous format.

In [7]:
from io import StringIO
import numpy as np
import pandas as pd
import requests

%config Completer.use_jedi = False

## 1. Read in the Raw Excel File from European Commission Website

In [2]:
NUTS_URL = 'https://ec.europa.eu/eurostat/documents/345175/629341/NUTS2021.xlsx'

In [3]:
res = requests.get(NUTS_URL)

In [12]:
if res.status_code == 200:
    res_xl = pd.ExcelFile(res.content, engine='openpyxl')

In [50]:
df_raw = pd.read_excel(res_xl, sheet_name='NUTS & SR 2021')

In [52]:
df_raw.head(10)

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,BE,Belgique/België,NaN,NaN,NaN,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BE1,NaN,Région de Bruxelles-Capitale/Brussels Hoofdste...,NaN,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BE10,NaN,NaN,Région de Bruxelles-Capitale/ Brussels Hoofdst...,NaN,2.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BE100,NaN,NaN,NaN,Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad,3.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BE2,NaN,Vlaams Gewest,NaN,NaN,1.0,1.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,BE21,NaN,NaN,Prov. Antwerpen,NaN,2.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,BE211,NaN,NaN,NaN,Arr. Antwerpen,3.0,1.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BE212,NaN,NaN,NaN,Arr. Mechelen,3.0,1.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,BE213,NaN,NaN,NaN,Arr. Turnhout,3.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,BE22,NaN,NaN,Prov. Limburg (BE),NaN,2.0,1.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2. Make Sure All Regions Have Standard Alphabet Names

In [89]:
df = df_raw.copy()

In [90]:
df['Unnamed: 9'] = df['Unnamed: 9'].astype(str)

In [91]:
df['Unnamed: 9'] = df['Unnamed: 9'].apply(lambda x: 'nan' if 'Latin' in x else x)

### 2a. Fix the countries first

In [92]:
df[(df['Unnamed: 9'] != 'nan') & (~df['Country'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
62,BG,България,NaN,NaN,NaN,0.0,2.0,63.0,NaN,BG,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
636,EL,Ελλάδα,NaN,NaN,NaN,0.0,8.0,637.0,NaN,EL,Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1111,CY,Κύπρος,NaN,NaN,NaN,0.0,13.0,1112.0,NaN,CY,Kýpros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1925,ME,Црна Гора,NaN,NaN,NaN,0.0,33.0,1923.0,NaN,ME,Crna Gora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1932,MK,Северна Македонија,NaN,NaN,NaN,0.0,34.0,1930.0,NaN,MK,Severna Makedonija,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,RS,Srbija/Сpбија,NaN,NaN,NaN,0.0,36.0,1964.0,NaN,RS,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
df['Country'] = np.where((df['Unnamed: 9'] != 'nan') & (~df['Country'].isna()), df['Unnamed: 10'], df['Country'])

In [94]:
df[(df['Unnamed: 9'] != 'nan') & (~df['Country'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
62,BG,Bulgaria,NaN,NaN,NaN,0.0,2.0,63.0,NaN,BG,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
636,EL,Elláda,NaN,NaN,NaN,0.0,8.0,637.0,NaN,EL,Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1111,CY,Kýpros,NaN,NaN,NaN,0.0,13.0,1112.0,NaN,CY,Kýpros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1925,ME,Crna Gora,NaN,NaN,NaN,0.0,33.0,1923.0,NaN,ME,Crna Gora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1932,MK,Severna Makedonija,NaN,NaN,NaN,0.0,34.0,1930.0,NaN,MK,Severna Makedonija,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,RS,Serbia,NaN,NaN,NaN,0.0,36.0,1964.0,NaN,RS,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2b. Next fix NUTS1

In [97]:
df[(~df['NUTS level 1'].isna()) & (~df['Unnamed: 10'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
63,BG3,NaN,Северна и Югоизточна България,NaN,NaN,1.0,2.0,64.0,NaN,BG3,Severna i Yugoiztochna Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,BG4,NaN,Югозападна и Южна централна България,NaN,NaN,1.0,2.0,87.0,NaN,BG4,Yugozapadna i Yuzhna tsentralna Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,BGZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,2.0,100.0,NaN,BGZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
637,EL3,NaN,Αττική,NaN,NaN,1.0,8.0,638.0,NaN,EL3,Attiki,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,EL4,NaN,"Νησιά Αιγαίου, Κρήτη",NaN,NaN,1.0,8.0,647.0,NaN,EL4,"Nisia Aigaiou, Kriti",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,EL5,NaN,Βόρεια Ελλάδα,NaN,NaN,1.0,8.0,660.0,NaN,EL5,Voreia Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,EL6,NaN,Κεντρική Ελλάδα,NaN,NaN,1.0,8.0,683.0,NaN,EL6,Kentriki Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706,ELZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,8.0,707.0,NaN,ELZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1112,CY0,NaN,Κύπρος,NaN,NaN,1.0,13.0,1113.0,NaN,CY0,Kýpros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,CYZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,13.0,1116.0,NaN,CYZ,EXTRA-REGIO NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926,ME0,NaN,Црна Гора,NaN,NaN,1.0,33.0,1924.0,NaN,ME0,Crna Gora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1929,MEZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,33.0,1927.0,NaN,MEZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,RS1,NaN,Србија - север,NaN,NaN,1.0,36.0,1965.0,NaN,RS1,Serbia - sever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1978,RS2,NaN,Србија - југ,NaN,NaN,1.0,36.0,1976.0,NaN,RS2,Serbia - jug,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,RSZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,36.0,1996.0,NaN,RSZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df['NUTS level 1'] = np.where((~df['NUTS level 1'].isna()) & (~df['Unnamed: 10'].isna()), df['Unnamed: 10'], df['NUTS level 1'])

In [99]:
df[(~df['NUTS level 1'].isna()) & (~df['Unnamed: 10'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
63,BG3,NaN,Severna i Yugoiztochna Bulgaria,NaN,NaN,1.0,2.0,64.0,NaN,BG3,Severna i Yugoiztochna Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,BG4,NaN,Yugozapadna i Yuzhna tsentralna Bulgaria,NaN,NaN,1.0,2.0,87.0,NaN,BG4,Yugozapadna i Yuzhna tsentralna Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,BGZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,2.0,100.0,NaN,BGZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
637,EL3,NaN,Attiki,NaN,NaN,1.0,8.0,638.0,NaN,EL3,Attiki,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,EL4,NaN,"Nisia Aigaiou, Kriti",NaN,NaN,1.0,8.0,647.0,NaN,EL4,"Nisia Aigaiou, Kriti",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,EL5,NaN,Voreia Elláda,NaN,NaN,1.0,8.0,660.0,NaN,EL5,Voreia Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,EL6,NaN,Kentriki Elláda,NaN,NaN,1.0,8.0,683.0,NaN,EL6,Kentriki Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706,ELZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,8.0,707.0,NaN,ELZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1112,CY0,NaN,Kýpros,NaN,NaN,1.0,13.0,1113.0,NaN,CY0,Kýpros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,CYZ,NaN,EXTRA-REGIO NUTS 1,NaN,NaN,1.0,13.0,1116.0,NaN,CYZ,EXTRA-REGIO NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926,ME0,NaN,Crna Gora,NaN,NaN,1.0,33.0,1924.0,NaN,ME0,Crna Gora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1929,MEZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,33.0,1927.0,NaN,MEZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,RS1,NaN,Serbia - sever,NaN,NaN,1.0,36.0,1965.0,NaN,RS1,Serbia - sever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1978,RS2,NaN,Serbia - jug,NaN,NaN,1.0,36.0,1976.0,NaN,RS2,Serbia - jug,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,RSZ,NaN,Extra-Regio NUTS 1,NaN,NaN,1.0,36.0,1996.0,NaN,RSZ,Extra-Regio NUTS 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2c. Next fix NUTS2

In [101]:
df[(~df['NUTS level 2'].isna()) & (~df['Unnamed: 11'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
64,BG31,NaN,NaN,Северозападен,NaN,2.0,2.0,65.0,NaN,BG31,NaN,Severozapaden,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,BG32,NaN,NaN,Северен централен,NaN,2.0,2.0,71.0,NaN,BG32,NaN,Severen tsentralen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,BG33,NaN,NaN,Североизточен,NaN,2.0,2.0,77.0,NaN,BG33,NaN,Severoiztochen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,BG34,NaN,NaN,Югоизточен,NaN,2.0,2.0,82.0,NaN,BG34,NaN,Yugoiztochen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,BG41,NaN,NaN,Югозападен,NaN,2.0,2.0,88.0,NaN,BG41,NaN,Yugozapaden,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,BG42,NaN,NaN,Южен централен,NaN,2.0,2.0,94.0,NaN,BG42,NaN,Yuzhen tsentralen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,BGZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,2.0,101.0,NaN,BGZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,EL30,NaN,NaN,Aττική,NaN,2.0,8.0,639.0,NaN,EL30,NaN,Attiki,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,EL41,NaN,NaN,Βόρειο Αιγαίο,NaN,2.0,8.0,648.0,NaN,EL41,NaN,Voreio Aigaio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,EL42,NaN,NaN,Νότιο Αιγαίο,NaN,2.0,8.0,652.0,NaN,EL42,NaN,Notio Aigaio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,EL43,NaN,NaN,Κρήτη,NaN,2.0,8.0,655.0,NaN,EL43,NaN,Kriti,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,EL51,NaN,NaN,"Aνατολική Μακεδονία, Θράκη",NaN,2.0,8.0,661.0,NaN,EL51,NaN,"Anatoliki Makedonia, Thraki",NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,EL52,NaN,NaN,Κεντρική Μακεδονία,NaN,2.0,8.0,667.0,NaN,EL52,NaN,Kentriki Makedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,EL53,NaN,NaN,Δυτική Μακεδονία,NaN,2.0,8.0,675.0,NaN,EL53,NaN,Dytiki Makedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,EL54,NaN,NaN,Ήπειρος,NaN,2.0,8.0,679.0,NaN,EL54,NaN,Ipeiros,NaN,NaN,NaN,NaN,NaN,NaN,NaN
683,EL61,NaN,NaN,Θεσσαλία,NaN,2.0,8.0,684.0,NaN,EL61,NaN,Thessalia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,EL62,NaN,NaN,Ιόνια Νησιά,NaN,2.0,8.0,688.0,NaN,EL62,NaN,Ionia Nisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,EL63,NaN,NaN,Δυτική Ελλάδα,NaN,2.0,8.0,693.0,NaN,EL63,NaN,Dytiki Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN
696,EL64,NaN,NaN,Στερεά Ελλάδα,NaN,2.0,8.0,697.0,NaN,EL64,NaN,Sterea Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN
702,EL65,NaN,NaN,Πελοπόννησος,NaN,2.0,8.0,703.0,NaN,EL65,NaN,Peloponnisos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,ELZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,8.0,708.0,NaN,ELZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,CY00,NaN,NaN,Κύπρος,NaN,2.0,13.0,1114.0,NaN,CY00,NaN,Kýpros,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,CYZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,13.0,1117.0,NaN,CYZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1927,ME00,NaN,NaN,Црна Гора,NaN,2.0,33.0,1925.0,NaN,ME00,NaN,Crna Gora,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1930,MEZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,33.0,1928.0,NaN,MEZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1968,RS11,NaN,NaN,Београдски регион,NaN,2.0,36.0,1966.0,NaN,RS11,NaN,City of Belgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970,RS12,NaN,NaN,Регион Војводине,NaN,2.0,36.0,1968.0,NaN,RS12,NaN,Autonomous Province of Vojvodina,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1979,RS21,NaN,NaN,Регион Шумадије и Западне Србије,NaN,2.0,36.0,1977.0,NaN,RS21,NaN,Region Šumadije i Zapadne Srbije,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988,RS22,NaN,NaN,Регион Јужне и Источне Србије,NaN,2.0,36.0,1986.0,NaN,RS22,NaN,Region Južne i Istočne Srbije,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,RSZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,36.0,1997.0,NaN,RSZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df['NUTS level 2'] = np.where((~df['NUTS level 2'].isna()) & (~df['Unnamed: 11'].isna()), df['Unnamed: 11'], df['NUTS level 2'])

In [103]:
df[(~df['NUTS level 2'].isna()) & (~df['Unnamed: 11'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
64,BG31,NaN,NaN,Severozapaden,NaN,2.0,2.0,65.0,NaN,BG31,NaN,Severozapaden,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,BG32,NaN,NaN,Severen tsentralen,NaN,2.0,2.0,71.0,NaN,BG32,NaN,Severen tsentralen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,BG33,NaN,NaN,Severoiztochen,NaN,2.0,2.0,77.0,NaN,BG33,NaN,Severoiztochen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,BG34,NaN,NaN,Yugoiztochen,NaN,2.0,2.0,82.0,NaN,BG34,NaN,Yugoiztochen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,BG41,NaN,NaN,Yugozapaden,NaN,2.0,2.0,88.0,NaN,BG41,NaN,Yugozapaden,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,BG42,NaN,NaN,Yuzhen tsentralen,NaN,2.0,2.0,94.0,NaN,BG42,NaN,Yuzhen tsentralen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,BGZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,2.0,101.0,NaN,BGZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,EL30,NaN,NaN,Attiki,NaN,2.0,8.0,639.0,NaN,EL30,NaN,Attiki,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,EL41,NaN,NaN,Voreio Aigaio,NaN,2.0,8.0,648.0,NaN,EL41,NaN,Voreio Aigaio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,EL42,NaN,NaN,Notio Aigaio,NaN,2.0,8.0,652.0,NaN,EL42,NaN,Notio Aigaio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,EL43,NaN,NaN,Kriti,NaN,2.0,8.0,655.0,NaN,EL43,NaN,Kriti,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,EL51,NaN,NaN,"Anatoliki Makedonia, Thraki",NaN,2.0,8.0,661.0,NaN,EL51,NaN,"Anatoliki Makedonia, Thraki",NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,EL52,NaN,NaN,Kentriki Makedonia,NaN,2.0,8.0,667.0,NaN,EL52,NaN,Kentriki Makedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,EL53,NaN,NaN,Dytiki Makedonia,NaN,2.0,8.0,675.0,NaN,EL53,NaN,Dytiki Makedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,EL54,NaN,NaN,Ipeiros,NaN,2.0,8.0,679.0,NaN,EL54,NaN,Ipeiros,NaN,NaN,NaN,NaN,NaN,NaN,NaN
683,EL61,NaN,NaN,Thessalia,NaN,2.0,8.0,684.0,NaN,EL61,NaN,Thessalia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,EL62,NaN,NaN,Ionia Nisia,NaN,2.0,8.0,688.0,NaN,EL62,NaN,Ionia Nisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,EL63,NaN,NaN,Dytiki Elláda,NaN,2.0,8.0,693.0,NaN,EL63,NaN,Dytiki Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN
696,EL64,NaN,NaN,Sterea Elláda,NaN,2.0,8.0,697.0,NaN,EL64,NaN,Sterea Elláda,NaN,NaN,NaN,NaN,NaN,NaN,NaN
702,EL65,NaN,NaN,Peloponnisos,NaN,2.0,8.0,703.0,NaN,EL65,NaN,Peloponnisos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,ELZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,8.0,708.0,NaN,ELZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,CY00,NaN,NaN,Kýpros,NaN,2.0,13.0,1114.0,NaN,CY00,NaN,Kýpros,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,CYZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,13.0,1117.0,NaN,CYZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1927,ME00,NaN,NaN,Crna Gora,NaN,2.0,33.0,1925.0,NaN,ME00,NaN,Crna Gora,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1930,MEZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,33.0,1928.0,NaN,MEZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1968,RS11,NaN,NaN,City of Belgrade,NaN,2.0,36.0,1966.0,NaN,RS11,NaN,City of Belgrade,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970,RS12,NaN,NaN,Autonomous Province of Vojvodina,NaN,2.0,36.0,1968.0,NaN,RS12,NaN,Autonomous Province of Vojvodina,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1979,RS21,NaN,NaN,Region Šumadije i Zapadne Srbije,NaN,2.0,36.0,1977.0,NaN,RS21,NaN,Region Šumadije i Zapadne Srbije,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988,RS22,NaN,NaN,Region Južne i Istočne Srbije,NaN,2.0,36.0,1986.0,NaN,RS22,NaN,Region Južne i Istočne Srbije,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,RSZZ,NaN,NaN,Extra-Regio NUTS 2,NaN,2.0,36.0,1997.0,NaN,RSZZ,NaN,Extra-Regio NUTS 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2d. Next fix NUTS3

In [104]:
df[(~df['NUTS level 3'].isna()) & (~df['Unnamed: 12'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
65,BG311,NaN,NaN,NaN,Видин,3.0,2.0,66.0,NaN,BG311,NaN,NaN,Vidin,NaN,NaN,NaN,NaN,NaN,NaN
66,BG312,NaN,NaN,NaN,Монтана,3.0,2.0,67.0,NaN,BG312,NaN,NaN,Montana,NaN,NaN,NaN,NaN,NaN,NaN
67,BG313,NaN,NaN,NaN,Враца,3.0,2.0,68.0,NaN,BG313,NaN,NaN,Vratsa,NaN,NaN,NaN,NaN,NaN,NaN
68,BG314,NaN,NaN,NaN,Плевен,3.0,2.0,69.0,NaN,BG314,NaN,NaN,Pleven,NaN,NaN,NaN,NaN,NaN,NaN
69,BG315,NaN,NaN,NaN,Ловеч,3.0,2.0,70.0,NaN,BG315,NaN,NaN,Lovech,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,RS226,NaN,NaN,NaN,Пиротска област,3.0,36.0,1992.0,NaN,RS226,NaN,NaN,Pirotska oblast,NaN,NaN,NaN,NaN,NaN,NaN
1995,RS227,NaN,NaN,NaN,Подунавска област,3.0,36.0,1993.0,NaN,RS227,NaN,NaN,Podunavska oblast,NaN,NaN,NaN,NaN,NaN,NaN
1996,RS228,NaN,NaN,NaN,Пчињска област,3.0,36.0,1994.0,NaN,RS228,NaN,NaN,Pčinjska oblast,NaN,NaN,NaN,NaN,NaN,NaN
1997,RS229,NaN,NaN,NaN,Топличка област,3.0,36.0,1995.0,NaN,RS229,NaN,NaN,Toplička oblast,NaN,NaN,NaN,NaN,NaN,NaN
2000,RSZZZ,NaN,NaN,NaN,Extra-Regio NUTS 3,3.0,36.0,1998.0,NaN,RSZZZ,NaN,NaN,Extra-Regio NUTS 3,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
df['NUTS level 3'] = np.where((~df['NUTS level 3'].isna()) & (~df['Unnamed: 12'].isna()), df['Unnamed: 12'], df['NUTS level 3'])

In [106]:
df[(~df['NUTS level 3'].isna()) & (~df['Unnamed: 12'].isna())]

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3,NUTS level,Country order,Region order,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
65,BG311,NaN,NaN,NaN,Vidin,3.0,2.0,66.0,NaN,BG311,NaN,NaN,Vidin,NaN,NaN,NaN,NaN,NaN,NaN
66,BG312,NaN,NaN,NaN,Montana,3.0,2.0,67.0,NaN,BG312,NaN,NaN,Montana,NaN,NaN,NaN,NaN,NaN,NaN
67,BG313,NaN,NaN,NaN,Vratsa,3.0,2.0,68.0,NaN,BG313,NaN,NaN,Vratsa,NaN,NaN,NaN,NaN,NaN,NaN
68,BG314,NaN,NaN,NaN,Pleven,3.0,2.0,69.0,NaN,BG314,NaN,NaN,Pleven,NaN,NaN,NaN,NaN,NaN,NaN
69,BG315,NaN,NaN,NaN,Lovech,3.0,2.0,70.0,NaN,BG315,NaN,NaN,Lovech,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,RS226,NaN,NaN,NaN,Pirotska oblast,3.0,36.0,1992.0,NaN,RS226,NaN,NaN,Pirotska oblast,NaN,NaN,NaN,NaN,NaN,NaN
1995,RS227,NaN,NaN,NaN,Podunavska oblast,3.0,36.0,1993.0,NaN,RS227,NaN,NaN,Podunavska oblast,NaN,NaN,NaN,NaN,NaN,NaN
1996,RS228,NaN,NaN,NaN,Pčinjska oblast,3.0,36.0,1994.0,NaN,RS228,NaN,NaN,Pčinjska oblast,NaN,NaN,NaN,NaN,NaN,NaN
1997,RS229,NaN,NaN,NaN,Toplička oblast,3.0,36.0,1995.0,NaN,RS229,NaN,NaN,Toplička oblast,NaN,NaN,NaN,NaN,NaN,NaN
2000,RSZZZ,NaN,NaN,NaN,Extra-Regio NUTS 3,3.0,36.0,1998.0,NaN,RSZZZ,NaN,NaN,Extra-Regio NUTS 3,NaN,NaN,NaN,NaN,NaN,NaN

### 2e. Only Keep Columns We Want & Rename

In [108]:
df = df[['Code 2021', 'Country', 'NUTS level 1', 'NUTS level 2', 'NUTS level 3']]
df.head(10)

,Code 2021,Country,NUTS level 1,NUTS level 2,NUTS level 3
0,BE,Belgique/België,NaN,NaN,NaN
1,BE1,NaN,Région de Bruxelles-Capitale/Brussels Hoofdste...,NaN,NaN
2,BE10,NaN,NaN,Région de Bruxelles-Capitale/ Brussels Hoofdst...,NaN
3,BE100,NaN,NaN,NaN,Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad
4,BE2,NaN,Vlaams Gewest,NaN,NaN
5,BE21,NaN,NaN,Prov. Antwerpen,NaN
6,BE211,NaN,NaN,NaN,Arr. Antwerpen
7,BE212,NaN,NaN,NaN,Arr. Mechelen
8,BE213,NaN,NaN,NaN,Arr. Turnhout
9,BE22,NaN,NaN,Prov. Limburg (BE),NaN

In [109]:
df = df.rename(columns={
    'Code 2021': 'Code',
    'NUTS level 1': 'NUTS1',
    'NUTS level 2': 'NUTS2',
    'NUTS level 3': 'NUTS3',
})

In [110]:
df.head(10)

,Code,Country,NUTS1,NUTS2,NUTS3
0,BE,Belgique/België,NaN,NaN,NaN
1,BE1,NaN,Région de Bruxelles-Capitale/Brussels Hoofdste...,NaN,NaN
2,BE10,NaN,NaN,Région de Bruxelles-Capitale/ Brussels Hoofdst...,NaN
3,BE100,NaN,NaN,NaN,Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad
4,BE2,NaN,Vlaams Gewest,NaN,NaN
5,BE21,NaN,NaN,Prov. Antwerpen,NaN
6,BE211,NaN,NaN,NaN,Arr. Antwerpen
7,BE212,NaN,NaN,NaN,Arr. Mechelen
8,BE213,NaN,NaN,NaN,Arr. Turnhout
9,BE22,NaN,NaN,Prov. Limburg (BE),NaN

## 3. Create Mapping Tables

### 3a. Create Country Mapping Table

First 2 letters only of the code along with the Country column

In [113]:
df_c = df[~df.Country.isna()][['Code', 'Country']]
df_c.head(10)

    Code          Country
0     BE  Belgique/België
62    BG         Bulgaria
102   CZ            Česko
129   DK          Danmark
150   DE      Deutschland
609   EE            Eesti
620   IE     Éire/Ireland
636   EL           Elláda
709   ES           España
798   FR           France

In [115]:
df.Country = df.Country.ffill()

### 3b. Create NUTS1 Only Table

Same thing again but include country and NUTS1

In [133]:
# drop the country specific rows
df = df.iloc[~df.index.isin(df_c.index)]

In [135]:
df_n1 = df[~df.NUTS1.isna()][['Code', 'Country', 'NUTS1']]
df_n1.head(10)

    Code          Country                                              NUTS1
1    BE1  Belgique/België  Région de Bruxelles-Capitale/Brussels Hoofdste...
4    BE2  Belgique/België                                      Vlaams Gewest
32   BE3  Belgique/België                                    Région wallonne
59   BEZ  Belgique/België                                 Extra-Regio NUTS 1
63   BG3         Bulgaria                    Severna i Yugoiztochna Bulgaria
86   BG4         Bulgaria           Yugozapadna i Yuzhna tsentralna Bulgaria
99   BGZ         Bulgaria                                 Extra-Regio NUTS 1
103  CZ0            Česko                                              Česko
126  CZZ            Česko                                 Extra-Regio NUTS 1
130  DK0          Danmark                                            Danmark

In [136]:
df.NUTS1 = df.NUTS1.ffill()

/Users/jamisonm/miniconda3/envs/epl/lib/python3.7/site-packages/pandas/core/generic.py:5170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

### 3c. Create NUTS2 Only Table

In [139]:
# drop the NUTS1 specific rows
df = df.iloc[~df.index.isin(df_n1.index)]

In [140]:
df_n2 = df[~df.NUTS2.isna()][['Code', 'Country', 'NUTS1', 'NUTS2']]
df_n2.head(10)

,Code,Country,NUTS1,NUTS2
2,BE10,Belgique/België,Région de Bruxelles-Capitale/Brussels Hoofdste...,Région de Bruxelles-Capitale/ Brussels Hoofdst...
5,BE21,Belgique/België,Vlaams Gewest,Prov. Antwerpen
9,BE22,Belgique/België,Vlaams Gewest,Prov. Limburg (BE)
13,BE23,Belgique/België,Vlaams Gewest,Prov. Oost-Vlaanderen
20,BE24,Belgique/België,Vlaams Gewest,Prov. Vlaams-Brabant
23,BE25,Belgique/België,Vlaams Gewest,Prov. West-Vlaanderen
33,BE31,Belgique/België,Région wallonne,Prov. Brabant Wallon
35,BE32,Belgique/België,Région wallonne,Prov. Hainaut
43,BE33,Belgique/België,Région wallonne,Prov. Liège
49,BE34,Belgique/België,Région wallonne,Prov. Luxembourg (BE)

In [141]:
df.NUTS2 = df.NUTS2.ffill()

### 3d. Create NUTS3 Only Table

In [142]:
# drop the NUTS2 specific rows
df = df.iloc[~df.index.isin(df_n2.index)]

In [143]:
df_n3 = df[~df.NUTS3.isna()][['Code', 'Country', 'NUTS1', 'NUTS2', 'NUTS3']]
df_n3.head(10)

,Code,Country,NUTS1,NUTS2,NUTS3
3,BE100,Belgique/België,Région de Bruxelles-Capitale/Brussels Hoofdste...,Région de Bruxelles-Capitale/ Brussels Hoofdst...,Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad
6,BE211,Belgique/België,Vlaams Gewest,Prov. Antwerpen,Arr. Antwerpen
7,BE212,Belgique/België,Vlaams Gewest,Prov. Antwerpen,Arr. Mechelen
8,BE213,Belgique/België,Vlaams Gewest,Prov. Antwerpen,Arr. Turnhout
10,BE223,Belgique/België,Vlaams Gewest,Prov. Limburg (BE),Arr. Tongeren
11,BE224,Belgique/België,Vlaams Gewest,Prov. Limburg (BE),Arr. Hasselt
12,BE225,Belgique/België,Vlaams Gewest,Prov. Limburg (BE),Arr. Maaseik
14,BE231,Belgique/België,Vlaams Gewest,Prov. Oost-Vlaanderen,Arr. Aalst
15,BE232,Belgique/België,Vlaams Gewest,Prov. Oost-Vlaanderen,Arr. Dendermonde
16,BE233,Belgique/België,Vlaams Gewest,Prov. Oost-Vlaanderen,Arr. Eeklo

In [147]:
df_n3[df_n3.Code.str.contains('UKN0')]

,Code,Country,NUTS1,NUTS2,NUTS3
1830,UKN06,United Kingdom,Northern Ireland,Northern Ireland,Belfast
1831,UKN07,United Kingdom,Northern Ireland,Northern Ireland,"Armagh City, Banbridge and Craigavon"
1832,UKN08,United Kingdom,Northern Ireland,Northern Ireland,"Newry, Mourne and Down"
1833,UKN09,United Kingdom,Northern Ireland,Northern Ireland,Ards and North Down
1834,UKN0A,United Kingdom,Northern Ireland,Northern Ireland,Derry City and Strabane
1835,UKN0B,United Kingdom,Northern Ireland,Northern Ireland,Mid Ulster
1836,UKN0C,United Kingdom,Northern Ireland,Northern Ireland,Causeway Coast and Glens
1837,UKN0D,United Kingdom,Northern Ireland,Northern Ireland,Antrim and Newtownabbey
1838,UKN0E,United Kingdom,Northern Ireland,Northern Ireland,Lisburn and Castlereagh
1839,UKN0F,United Kingdom,Northern Ireland,Northern Ireland,Mid and East Antrim
1840,UKN0G,United Kingdom,Northern Ireland,Northern Ireland,Fermanagh and Omagh